language: node_js
node_js:
- '6'
script:
- npm run lint
- npm run test
deploy:
  provider: npm
  email: breath103@gmail.com
  skip_cleanup: true
  api_key:
    secure: wDx33l3Su3ZCqG9EEvyqaM5Z/9gH/zDjkMQsznOWynjgSckQIjGwffBcWheVYAVEQKAGgBfULRi5PAu4epN4qeitqZ9skVmtT+aM6Zz/K/5AU1N1c8ZhkprZwTuJZn3bMKMvmum2T6MlmYSnXlLXdlbXW86f03un+2mT7YfQMC0y6aNNX3ywzxnbcs4KD7orfJutcY+TDgvHgOoK1sTF6vj6CS5ZhDtKCel+1ICL1IVPwXvrGYvgYFtFcbLxa/DzUy2ZwLMn+7Xa+nusE5akoZsxXO+kY0z2JE/TwIT0uJU38uqNPoUEj56pwTJ4l3kSil9oQxeyuqcZGruLxZf8qqk72ujdAxIrhm4F/CgmqL70aC0umfUk3BeKBoFi9Sio9OltOvm74cJeIWirfm7BOGEOwG+kG7ou+/NeVcawnk2aw7YjKrxMt2qClOEGgaH9cJADOUrDgJ2AoKl8gESB0ZxXXNj3BSnD52IOWz/OTEBNEHiKClgGKvsAM0rsiFvZcYCUDB/kP7YR2OIkXWrUvTbpB8kr36dVfso1gepmC4JMU07zMqiej2Zr08n8fjM/oTZHsplX4+3fjjivnVq9hKCu9yfYHwSMJs+/uPOBJd3Aj88vf+mNLMTL0Skog1FlNnF6EtkufZosZ6tUi5g4ZNizhgNeboKYzktnIKX93dc=
  on:
    branch: master
